jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Initialize Terraform
        run: |
          cd infra   # Navigate to the directory containing Terraform files
          terraform init

      - name: Terraform Plan or Apply
        run: |
          cd infra   # Navigate to the directory containing Terraform files
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Applying changes to main infrastructure..."
            terraform apply -auto-approve
          else
            echo "Planning changes for branch: ${{ github.ref_name }}"
            terraform plan
          fi
